version: '2.2'
services:
  user-registry:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:80
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432